# Site Settings
locale                   : "en-UK"
title                    : "Matt Arderne"
author                   : "Matt Arderne"
description              : "Data Engineering."
url                      : "https://rdrn.dev"
home                     : "/"
avatar                   : "/assets/images/face.png"
location                 : "UK"
github                   : "mattarderne"
linkedin                 : "m-ard"
twitter                  : "mattarderne"
email                    : "matt@sea.dev"
buzzwords                : "Fintech • Data"
company                  : ""
company_address          : ""
aboutme                  : "Hi, my name is Matt, I'm an experienced engineer with a proven track record building data systems."

plugins:
#  - jekyll-sitemap
  - jekyll-feed

# Reading Files
exclude:
  - .sass-cache
  - Gemfile
  - LICENSE
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

permalink: /:title/

compress_html:
  clippings: all
